### PR TITLE
Skip over CDATA

### PR DESCRIPTION
**Pull request by mniip**
Addresses #1 
- Don't fail the parse if we run into a CDATA.
- Do the same to CDATA as we do to comments: leave it up to the downstream user to parse them.

### CODE REVIEW

**Comment by mniip** [comment]
@ndmitchell gentle prod?

**Comment by ndmitchell** [comment]
Thanks for the patch. I reviewed it by eye and it looks great. Can we get a test in https://github.com/ndmitchell/hexml/blob/master/src/Main.hs as well? It's pretty subtle doing this coding, and a test would give a lot of confidence.

I'm afraid I'm going to be too busy to land over the next 2 weeks, but will endeavor to do it when I'm free again after that.

**Comment by mniip** [comment]
@ndmitchell ping?

**Comment by ndmitchell** [comment]
Thanks! I released Hexml 0.3.5 with this change.

**Pull request merged**
